[tool.poetry]
name = "backend"
version = "1.1"
description = "test"
authors = ["Moorthy <moorthy.chandiran21@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "^0.34.2"
fastapi = "^0.95.1"
pyodbc = "4.0.32"  # Update to a specific version that is compatible

