[tool.poetry]
name = "backend"
version = "1.1"
description = "test"
authors = ["Moorthy <moorthy.chandiran21@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
